"""Default crawl tuning (used by spider and GUI)."""


class CrawlDefaults:
    MAX_PAGES_PER_DOMAIN = 15
    EARLY_STOP_EMAIL_COUNT = 5
    MAX_DEPTH_SLASHES = 6
    PRIORITY_LINK_CAP = 12
    NORMAL_LINK_CAP = 6
    CONCURRENT_REQUESTS = 8
    CONCURRENT_REQUESTS_PER_DOMAIN = 2
    DOWNLOAD_DELAY = 0.75
    AUTOTHROTTLE_TARGET_CONCURRENCY = 1.5
